def alloc_emergency_exception_buf(size):
    pass
